<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Sportif
 */
require_once('Sportif.class.php');

class Footballer extends Sportif {

	/**
	 * 
	 * @var string
	 * @access public
	 */
	public  $team;


}
?>