<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Sportif {

	/**
	 * 
	 * @var array
	 * @access private
	 */
	private  $sports;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $birthplace;

	/**
	 * 
	 * @var string
	 * @access public
	 */
	public  $name;


	/**
	 * @access public
	 * @return bool
	 */

	public  function create() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public  function delete() {

	}


	/**
	 * @access public
	 * @param string $name 
	 */

	public  function setName($name = "diego") {

	}


}
?>