<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Sportif
 */
require_once('Sportif.class.php');

class Tennisman extends Sportif {

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $rank;


}
?>